gemeinde_aliases = {
    "Altenstadt": ["Altenstadt"],
    "Bad Nauheim": ["Bad Nauheim"],
    "Bad Vilbel": ["Bad Vilbel"],
    "Büdingen": ["Büdingen"],
    "Butzbach": ["Butzbach", "Butzbach Friedrich-Ludwig-Weidig-Stadt"],
    "Echzell": ["Echzell"],
    "Florstadt": ["Florstadt"],
    "Friedberg (Hessen)": ["Friedberg (Hessen)", "Friedberg", "Friedberg Hessen"],
    "Gedern": ["Gedern"],
    "Glauburg": ["Glauburg"],
    "Hirzenhain": ["Hirzenhain"],
    "Karben": ["Karben"],
    "Kefenrod": ["Kefenrod"],
    "Limeshain": ["Limeshain"],
    "Münzenberg": ["Münzenberg"],
    "Nidda": ["Nidda"],
    "Niddatal": ["Niddatal"],
    "Ober-Mörlen": ["Ober-Mörlen"],
    "Ortenberg": ["Ortenberg"],
    "Ranstadt": ["Ranstadt"],
    "Reichelsheim (Wetterau)": ["Reichelsheim (Wetterau)", "Reichelsheim", "Reichelsheim Wetterau"],
    "Rockenberg": ["Rockenberg"],
    "Rosbach v. d. Höhe": ["Rosbach v. d. Höhe", "Rosbach v d Höhe"],
    "Wölfersheim": ["Wölfersheim"],
    "Wöllstadt": ["Wöllstadt"]
}
